[project]
name = "trismik"
dynamic = ["version"]
description = ""
authors = [
    { name = "Bartosz Kielczewski", email = "bk352@cam.ac.uk" },
    { name = "Peter Monks", email = "peter.monks@systemc.com" },
    { name = "Greg Holdridge", email = "greg.holdridge@systemc.com" }
]
readme = "README.md"
requires-python = ">=3.8"

[tool.poetry]
version = "0.9.1"  # base version
packages = [{ include = "trismik", from = "src" }]

[tool.poetry.dependencies]
httpx = "^0.27.2"
python-dateutil = "^2.9.0.post0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
python-dotenv = "^1.0.1"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "class"
